lint:
  plugins:
    - './local-plugin.js'

  extends:
    - recommended
    - local/all
  rules:
    operation-2xx-response: warning
    operation-description: off
    path-http-verbs-order: error
  transformers:
    local/duplicate-description: off